export const statuteList = [
  {
    title: "§ 1 Postanowienia wstępne",
    content:
      "Sklep internetowy dostępny pod adresem internetowym magdalenakapela.com prowadzony jest przez KAPELLA ART. SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ. z siedzibą w 43-300 Bielsko-Biała, ul. prof. dr Mieczysława Michałowicza 12, wpisaną do rejestru przedsiębiorców Krajowego Rejestru Sądowego pod numerem KRS: 0000830738, NIP: 5472217560, REGON: 38562239300000.",
  },
  {
    title: "§ 2 Definicje",
    content: [
      "1/ Konsument – osoba fizyczna zawierająca ze Sprzedawcą umowę w ramach Sklepu, której przedmiot nie jest związany bezpośrednio z jej działalnością gospodarczą lub zawodową.",
      "2/ Sprzedawca – KAPELLA ART. SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ. z siedzibą w 43-300 Bielsko-Biała, ul. prof. dr Mieczysława Michałowicza 12, wpisaną do rejestru przedsiębiorców Krajowego Rejestru Sądowego pod numerem KRS: 0000830738, NIP: 5472217560, REGON: 38562239300000.",
      "3/ Klient – każdy podmiot dokonujący zakupów za pośrednictwem Sklepu.",
      "4/ Przedsiębiorca – osoba fizyczna, osoba prawna i jednostka organizacyjna niebędąca osobą prawną, której odrębna ustawa przyznaje zdolność prawną, wykonująca we własnym imieniu działalność gospodarczą, która korzysta ze Sklepu.",
      "5/ Sklep – sklep internetowy prowadzony przez Sprzedawcę pod adresem internetowym magdalenakapela.pl",
      "6/ Umowa zawarta na odległość – umowa zawarta z Klientem w ramach zorganizowanego systemu zawierania umów na odległość (w ramach Sklepu), bez jednoczesnej fizycznej obecności stron, z wyłącznym wykorzystaniem jednego lub większej liczby środków porozumiewania się na odległość do chwili zawarcia umowy włącznie.",
      "7/ Regulamin – niniejszy regulamin Sklepu.",
      "8/ Zamówienie – oświadczenie woli Klienta składane za pomocą Formularza Zamówienia i zmierzające bezpośrednio do zawarcia Umowy Sprzedaży Produktu lub Produktów ze Sprzedawcą.",
      "9/ Konto – konto klienta w Sklepie, na którym gromadzone są dane podane przez Klienta oraz informacje o złożonych przez niego Zamówieniach w Sklepie.",
      "10/ Formularz rejestracji – formularz dostępny w Sklepie, umożliwiający utworzenie Konta.",
      "11/ Formularz zamówienia – interaktywny formularz dostępny w Sklepie umożliwiający złożenie Zamówienia, w szczególności poprzez dodanie Produktów do Koszyka oraz określenie warunków Umowy Sprzedaży, w tym sposobu dostawy i płatności.",
      "12/ Koszyk – element oprogramowania Sklepu, w którym widoczne są wybrane przez Klienta Produkty do zakupu, a także istnieje możliwość ustalenia i modyfikacji danych Zamówienia, w szczególności ilości produktów.",
      "13/ Produkt – dostępna w Sklepie rzecz ruchoma/usługa będąca przedmiotem Umowy Sprzedaży między Klientem a Sprzedawcą.",
      "14/ Umowa Sprzedaży – umowa sprzedaży Produktu zawierana albo zawarta między Klientem a Sprzedawcą za pośrednictwem Sklepu.",
      "15/ Prawo odstąpienia – możliwość Klienta będącego Konsumentem do odstąpienia od Umowy na odległość.",
    ],
  },
  {
    title: "§ 3 Kontakt ze Sklepem",
    content: [
      "1/ Adresem e-mail Sklepu jest: sklep@magdalenakapela.pl",
      "2/ Adresem do korespondencji jest: KAPELLA ART. SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ. ul. prof. dr Mieczysława Michałowicza 12, 43-300 Bielsko-Biała.",
    ],
  },
  {
    title: "§ 4 Warunki korzystania ze Sklepu",
    content:
      "1/ Warunkiem koniecznym korzystania ze Sklepu jest posiadanie przez Klienta urządzenia końcowego, które spełnia minimalne wymagania techniczne umożliwiające korzystanie z Serwisu, w tym: komputera, laptopa, tabletu lub innego urządzenia końcowego z dostępem do Internetu, zainstalowanego oprogramowania w tym przeglądarki internetowej, pozwalającej wyświetlać strony internetowe.",
    additionalRequirements:
      "Klient powinien także spełnić następujące minimalne wymagania techniczne, aby korzystać z usług elektronicznych świadczonych przez Sprzedawcę: posiadać aktywne konto poczty elektronicznej (e-mail), posługiwać się przeglądarką internetową Internet Explorer (wersja minimum 11), Mozilla Firefox (wersja minimum 10), Google Chrome (wersja minimum 10), Opera (wersja minimum 10) lub Safari (wersja minimum 5).",
  },
  {
    title: "§ 5 Informacje ogólne",
    content: [
      "1/ Sprzedawca nie ponosi odpowiedzialności za zakłócenia, w tym przerwy w funkcjonowaniu Sklepu spowodowane siłą wyższą, niedozwolonym działaniem osób trzecich lub niekompatybilnością Sklepu internetowego z infrastrukturą techniczną Klienta.",
      "2/ Przeglądanie asortymentu Sklepu nie wymaga zakładania Konta. Składanie zamówień przez Klienta na Produkty znajdujące się w asortymencie Sklepu możliwe jest albo po założeniu Konta zgodnie z postanowieniami § 6 Regulaminu albo przez podanie niezbędnych danych osobowych i adresowych umożliwiających realizację Zamówienia bez zakładania Konta.",
      "3/ Ceny podane w Sklepie są podane w polskich złotych i są cenami brutto (uwzględniają podatek VAT).",
      "4/ Na końcową (ostateczną) kwotę do zapłaty przez Klienta składa się cena za Produkt oraz koszt dostawy (w tym opłaty za transport, dostarczenie i usługi pocztowe), o której Klient jest informowany na stronach Sklepu w trakcie składania Zamówienia, w tym także w chwili wyrażenia woli związania się Umową Sprzedaży.",
      "5/ W przypadku Umowy obejmującej prenumeratę lub świadczenie usług na czas nieoznaczony końcową (ostateczną) ceną jest łączna cena obejmująca wszystkie płatności za okres rozliczeniowy.",
      "6/ Gdy charakter przedmiotu Umowy nie pozwala, rozsądnie oceniając, na wcześniejsze obliczenie wysokości końcowej (ostatecznej) ceny, informacja o sposobie, w jaki cena będzie obliczana, a także o opłatach za transport, dostarczenie, usługi pocztowe oraz o innych kosztach, będzie podana w Sklepie w opisie Produktu.",
    ],
  },
  {
    title: "§ 6 Zakładanie Konta w Sklepie",
    content: [
      "1/ Aby założyć Konto w Sklepie, należy wypełnić Formularz rejestracji. Niezbędne jest podanie następujących danych Imię i Nazwisko, adres e-mail.",
      "2/ Założenie Konta w Sklepie jest darmowe.",
      "3/ Logowanie się na Konto odbywa się poprzez podanie loginu i hasła ustanowionych w Formularzu rejestracji.",
      "4/ Klient ma możliwość w każdej chwili, bez podania przyczyny i bez ponoszenia z tego tytułu jakichkolwiek opłat usunąć Konto poprzez wysłanie stosownego żądania do Sprzedawcy, w szczególności za pośrednictwem poczty elektronicznej lub pisemnie na adresy podane w § 3.",
    ],
  },
  {
    title: "§ 7 Zasady składania Zamówienia",
    content: [
      "W celu złożenia Zamówienia należy:",
      "a/ zalogować się do Sklepu (opcjonalnie);",
      "b/ wybrać Produkt będący przedmiotem Zamówienia, a następnie kliknąć przycisk „Do koszyka” (lub równoznaczny);",
      "c/ zalogować się lub skorzystać z możliwości złożenia Zamówienia bez rejestracji;",
      "d/ jeżeli wybrano możliwość złożenia Zamówienia bez rejestracji – wypełnić Formularz zamówienia poprzez wpisanie danych odbiorcy Zamówienia oraz adresu, na który ma nastąpić dostawa Produktu, wybrać rodzaj przesyłki (sposób dostarczenia Produktu), wpisać dane do faktury, jeśli są inne niż dane odbiorcy Zamówienia,",
      "e/ kliknąć przycisk potwierdzający zamówienia, np. “Zamawiam i płacę” oraz potwierdzić zamówienie, klikając w link przesłany w wiadomości e-mail,",
      "f/ wybrać jeden z dostępnych sposobów płatności i w zależności od sposobu płatności, opłacić zamówienie w określonym terminie, z zastrzeżeniem § 8 pkt 3.",
    ],
  },
  {
    title: "§ 8 Oferowane metody dostawy oraz płatności",
    content: [
      "1/ Klient może skorzystać z następujących metod dostawy lub odbioru zamówionego Produktu:",
      "a/ Przesyłka pocztowa, przesyłka pocztowa pobraniowa,",
      "b/ Przesyłka kurierska, przesyłka kurierska pobraniowa,",
      "c/ Odbiór osobisty dostępny pod adresem: 43-300 Bielsko-Biała, ul. prof. dr Mieczysława Michałowicza 12.",
      "2/ Klient może skorzystać z następujących metod płatności:",
      "a/ Płatność za pobraniem",
      "b/ Płatność przelewem na konto Sprzedawcy",
      "c/ Płatności elektroniczne",
      "d/ Płatność kartą płatniczą.",
      "3/ Szczegółowe informacje na temat metod dostawy oraz akceptowalnych metod płatności znajdują się za stronach Sklepu.",
    ],
  },
  {
    title: "§ 9 Wykonanie umowy sprzedaży",
    content: [
      "1/ Zawarcie Umowy Sprzedaży między Klientem a Sprzedawcą następuje po uprzednim złożeniu przez Klienta Zamówienia za pomocą Formularza zamówienia w Sklepie internetowym zgodnie z § 7 Regulaminu.",
      "2/ Po złożeniu Zamówienia Sprzedawca niezwłocznie potwierdza jego otrzymanie oraz jednocześnie przyjmuje Zamówienie do realizacji. Potwierdzenie otrzymania Zamówienia i jego przyjęcie do realizacji następuje poprzez przesłanie przez Sprzedawcę Klientowi stosownej wiadomości e-mail na podany w trakcie składania Zamówienia adres poczty elektronicznej Klienta, która zawiera co najmniej oświadczenia Sprzedawcy o otrzymaniu Zamówienia i o jego przyjęciu do realizacji oraz potwierdzenie zawarcia Umowy Sprzedaży. Z chwilą otrzymania przez Klienta powyższej wiadomości e-mail zostaje zawarta Umowa Sprzedaży między Klientem a Sprzedawcą.",
      "3/ W przypadku wyboru przez Klienta:",
      "a/ płatności przelewem, płatności elektronicznych albo płatności kartą płatniczą, Klient obowiązany jest do dokonania płatności w terminie 1 dnia kalendarzowego od dnia zawarcia Umowy Sprzedaży – w przeciwnym razie zamówienie zostanie anulowane.",
      "b/ płatności za pobraniem przy odbiorze przesyłki, Klient obowiązany jest do dokonania płatności przy odbiorze przesyłki.",
      "4/ Jeżeli Klient wybrał sposób dostawy inny niż odbiór osobisty, Produkt zostanie wysłany przez Sprzedawcę w terminie wskazanym w jego opisie (z zastrzeżeniem ustępu 5 niniejszego paragrafu), w sposób wybrany przez Klienta podczas składania Zamówienia.",
      "a/ W przypadku zamówienia Produktów o różnych terminach dostawy, terminem dostawy jest najdłuższy podany termin.",
      "b/ W przypadku zamówienia Produktów o różnych terminach dostawy, Klient ma możliwość żądania dostarczenia Produktów częściami lub też dostarczenia wszystkich Produktów po skompletowaniu całego zamówienia.",
      "5/ Początek biegu terminu dostawy Produktu do Klienta liczy się w następujący sposób:",
      "a/ W przypadku wyboru przez Klienta sposobu płatności przelewem, płatności elektroniczne lub kartą płatniczą – od dnia uznania rachunku bankowego Sprzedawcy.",
      "b/ W przypadku wyboru przez Klienta sposobu płatności za pobraniem – od dnia zawarcia Umowy Sprzedaży,",
      "6/ W przypadku wyboru przez Klienta odbioru osobistego Produktu, Produkt będzie gotowy do odbioru przez Klienta w terminie wskazanym w opisie Produktu. O gotowości Produktu do odbioru Klient zostanie dodatkowo poinformowany przez Sprzedawcę poprzez przesłanie stosownej wiadomości e-mail na podany w trakcie składania Zamówienia adres poczty elektronicznej Klienta.",
      "7/ Dostawa Produktu odbywa się wyłącznie na terenie Polski.",
      "8/ Dostawa Produktu do Klienta jest odpłatna, chyba że Umowa Sprzedaży stanowi inaczej. Koszty dostawy Produktu (w tym opłaty za transport, dostarczenie i usługi pocztowe) są wskazywane Klientowi na stronach Sklepu internetowego w zakładce „Koszty dostawy” oraz w trakcie składania Zamówienia, w tym także w chwili wyrażenia przez Klienta woli związania się Umową Sprzedaży.",
      "9/ Odbiór osobisty Produktu przez Klienta jest bezpłatny.",
    ],
  },
  {
    title: "§ 10 Prawo odstąpienia od umowy",
    content: [
      "1/ Konsument może w terminie 14 dni odstąpić od Umowy Sprzedaży bez podania przyczyny.",
      "2/ Bieg terminu określonego w ust. 1 rozpoczyna się od dostarczenia Produktu Konsumentowi lub wskazanej przez niego osobie innej niż przewoźnik.",
      "3/ W przypadku Umowy, która obejmuje wiele Produktów, które są dostarczane osobno, partiami lub w częściach, termin wskazany w ust. 1 biegnie od dostawy ostatniej rzeczy, partii lub części.",
      "4/ W przypadku Umowy, która polega na regularnym dostarczaniu Produktów przez czas oznaczony (prenumerata), termin wskazany w ust. 1 biegnie od objęcia w posiadanie pierwszej z rzeczy.",
      "5/ Konsument może odstąpić od Umowy, składając Sprzedawcy oświadczenie o odstąpieniu od Umowy. Do zachowania terminu odstąpienia od Umowy wystarczy wysłanie przez Konsumenta oświadczenia przed upływem tego terminu.",
      "6/ Oświadczenie o odstąpieniu może być wysłane za pomocą tradycyjnej poczty bądź drogą elektroniczną poprzez przesłanie oświadczenia na adres e-mail Sprzedawcy. Oświadczenie można złożyć również na formularzu, którego wzór stanowi załącznik do ustawy z dnia 30 maja 2014 roku o prawach konsumenta, jednak nie jest to obowiązkowe.",
      "7/ Skutki odstąpienia od Umowy:",
      "a/ W przypadku odstąpienia od Umowy zawartej na odległość Umowę uważa się za niezawartą.",
      "b/ W przypadku odstąpienia od Umowy Sprzedawca zwraca Konsumentowi niezwłocznie, nie później niż w terminie 14 dni od dnia otrzymania oświadczenia Konsumenta o odstąpieniu od Umowy, wszystkie dokonane przez niego płatności, w tym koszty dostarczenia rzeczy, z wyjątkiem dodatkowych kosztów wynikających z wybranego przez Konsumenta sposobu dostarczenia innego niż najtańszy zwykły sposób dostarczenia oferowany przez Sprzedawcę.",
      "c/ Zwrotu płatności Sprzedawca dokona przy użyciu takich samych metod płatności, jakie zostały przez Konsumenta użyte w pierwotnej transakcji, chyba że Konsument wyraźnie zgodził się na inne rozwiązanie, które nie będzie się wiązało dla niego z żadnymi kosztami.",
      "d/ Sprzedawca może wstrzymać się ze zwrotem płatności do czasu otrzymania Produktu z powrotem i umożliwienia mu zbadania stanu produktu.",
      "e/ Konsument powinien odesłać Produkt na adres Sprzedawcy podany w niniejszym Regulaminie niezwłocznie, nie później niż 14 dni od dnia, w którym poinformował Sprzedawcę o odstąpieniu od Umowy. Termin zostanie zachowany, jeśli Konsument odeśle Produkt przed upływem terminu 14 dni.",
      "f/ Konsument ponosi bezpośrednie koszty zwrotu Produktu, także koszty zwrotu Produktu, jeśli ze względu na swój charakter Produkt ten nie mógł zostać w zwykłym trybie odesłany pocztą.",
      "g/ Konsument odpowiada za zmniejszenie wartości Produktu wynikające z korzystania z niego w sposób inny niż było to konieczne do stwierdzenia charakteru, cech i funkcjonowania Produktu. W wypadku obrazów –  korzystanie z Produktu poprzez otwarcie przez Konsumenta jego oryginalnego opakowania i wystawienie na działanie warunków atmosferycznych skutkuje uznaniem, że zmniejszenie wartości Produktu nastąpiło w wymiarze 100%, Produkt nie nadaje się bowiem do ponownego wystawienia w charakterze oryginalnym.",
      "8/ Prawo odstąpienia od Umowy zawartej na odległość nie przysługuje Konsumentowi w odniesieniu do Umów:",
      "- w której przedmiotem świadczenia jest rzecz nieprefabrykowana, wyprodukowana według specyfikacji Konsumenta lub służąca zaspokojeniu jego zindywidualizowanych potrzeb.",
      "- w której przedmiotem świadczenia jest rzecz ulegająca szybkiemu zepsuciu lub mająca krótki termin przydatności do użycia.",
      "- w której przedmiotem świadczenia jest rzecz dostarczana w zapieczętowanym opakowaniu, której po otwarciu opakowania nie można zwrócić ze względu na ochronę zdrowia lub ze względów higienicznych, jeżeli opakowanie zostało otwarte po dostarczeniu.",
      "- w której przedmiotem świadczenia są rzeczy, które po dostarczeniu, ze względu na swój charakter, zostają nierozłącznie połączone z innymi rzeczami.",
      "- w której przedmiotem świadczenia są napoje alkoholowe, których cena została uzgodniona przy zawarciu Umowy Sprzedaży, a których dostarczenie może nastąpić dopiero po upływie 30 dni i których wartość zależy od wahań na rynku, nad którymi Sprzedawca nie ma kontroli.",
      "- w której Konsument wyraźnie żądał, aby Sprzedawca do niego przyjechał w celu dokonania pilnej naprawy lub konserwacji; jeżeli Sprzedawca świadczy dodatkowo inne usługi niż te, których wykonania Konsument żądał, lub dostarcza rzeczy inne niż części zamienne niezbędne do wykonania naprawy lub konserwacji, prawo odstąpienia od Umowy przysługuje Konsumentowi w odniesieniu do dodatkowych usług lub rzeczy.",
      "- w której przedmiotem świadczenia są nagrania dźwiękowe lub wizualne albo programy komputerowe dostarczane w zapieczętowanym opakowaniu, jeżeli opakowanie zostało otwarte po dostarczeniu.",
      "- o dostarczanie dzienników, periodyków lub czasopism, z wyjątkiem umowy o prenumeratę.",
      "- zawartej w drodze aukcji publicznej.",
      "- o świadczenie usług, jeżeli Sprzedawca wykonał w pełni usługę za wyraźną zgodą Konsumenta, który został poinformowany przed rozpoczęciem świadczenia, że po spełnieniu świadczenia przez Sprzedawcę utraci prawo odstąpienia od Umowy.",
      "- w której przedmiotem świadczenia są pliki cyfrowe, które nie są zapisane na nośniku materialnym, jeżeli spełnianie świadczenia rozpoczęło się za wyraźną zgodą Konsumenta przed upływem terminu do odstąpienia od Umowy i po poinformowaniu go przez Sprzedawcę o utracie prawa odstąpienia od Umowy.",
      "- o dostarczanie treści cyfrowych, które nie są zapisane na nośniku materialnym, jeżeli spełnianie świadczenia rozpoczęło się za wyraźną zgodą Konsumenta przed upływem terminu do odstąpienia od Umowy i po poinformowaniu go przez Sprzedawcę o utracie prawa odstąpienia od Umowy.",
    ],
  },
  {
    title: "§ 11 Reklamacja",
    content: [
      "1/ Sprzedawca jest zobowiązany dostarczyć Produkt bez wad.",
      "2/ Jeżeli Produkt posiada wady, Klient może złożyć reklamację dotyczącą zawartej Umowy Sprzedaży.",
      "3/ Reklamację można złożyć na piśmie na adres Sprzedawcy podany w niniejszym Regulaminie lub drogą elektroniczną za pośrednictwem poczty elektronicznej na adres e-mail Sprzedawcy podany w niniejszym Regulaminie.",
      "4/ Preferowany przez Sprzedawcę sposób składania reklamacji przez Klienta to wypełnienie Formularza reklamacyjnego stanowiącego załącznik nr 2 do niniejszego Regulaminu.",
      "5/ W zgłoszeniu reklamacyjnym Klient winien podać swoje imię, nazwisko, adres do korespondencji, adres e-mail, datę zawarcia Umowy Sprzedaży, rodzaj wady Produktu oraz żądanie Klienta.",
      "6/ Sprzedawca rozpatruje reklamację niezwłocznie, nie później niż w terminie 14 dni od dnia jej otrzymania. Odpowiedź Sprzedawcy w sprawie reklamacji jest wysyłana na wskazany przez Klienta adres e-mail lub inny podany w zgłoszeniu reklamacyjnym sposób.",
      "7/ W przypadku gdy weryfikacja reklamacji będzie wymagała dodatkowych informacji od Klienta, Sprzedawca może poprosić Klienta o ich dostarczenie.",
      "8/ Klient, będący Konsumentem, ma możliwość skorzystania z pozasądowych sposobów rozpatrywania reklamacji i dochodzenia roszczeń. Dla polubownego rozstrzygnięcia sporu Klient może zwrócić się do:",
      "a/ Stałego Polubownego Sądu Konsumenckiego przy Wojewódzkim Inspektoracie Inspekcji Handlowej w Bielsku-Białej,",
      "b/ Wojewódzkiego Inspektora Inspekcji Handlowej w Bielsku-Białej.",
      "9/ Informacje o sposobach dostępu do ww. trybów i procedur polubownego rozstrzygania sporów, siedzibach oraz obszarach właściwości terytorialnej ww. podmiotów udostępniane są przez ww. podmioty.",
    ],
  },
  {
    title: "§ 12 Dane osobowe w Sklepie internetowym",
    content: [
      "1/ Administratorem danych osobowych Klientów zbieranych za pośrednictwem Sklepu internetowego jest Sprzedawca.",
      "2/ Dane osobowe Klientów zbierane przez administratora za pośrednictwem Sklepu internetowego zbierane są w celu realizacji Umowy Sprzedaży, a jeżeli Klient wyrazi na to zgodę – także w celach marketingowych.",
      "3/ Administratorem danych osobowych Klientów zbieranych za pośrednictwem Sklepu internetowego jest Sprzedawca.",
      "4/ Administratorem danych osobowych Klientów zbieranych za pośrednictwem Sklepu internetowego jest Sprzedawca.",
      "5/ Administratorem danych osobowych Klientów zbieranych za pośrednictwem Sklepu internetowego jest Sprzedawca.",
      "6/ Szczegółowe informacje dotyczące przetwarzania danych osobowych Klientów przez Sprzedawcę znajdują się w Polityce prywatności zamieszczonej na stronach Sklepu internetowego.",
    ],
  },
  {
    title: "§ 13 Dane osobowe w Sklepie internetowym",
    content: [
      "1/ Administratorem danych osobowych Klientów zbieranych za pośrednictwem Sklepu internetowego jest Sprzedawca.",
      "2/ Dane osobowe Klientów zbierane przez administratora za pośrednictwem Sklepu internetowego zbierane są w celu realizacji Umowy Sprzedaży, a jeżeli Klient wyrazi na to zgodę – także w celu marketingowym.",
      "3/ Odbiorcami danych osobowych Klientów Sklepu internetowego mogą być:",
      "   a/ W przypadku Klienta, który korzysta w Sklepie internetowym ze sposobu dostawy przesyłką pocztową lub przesyłką kurierską, Administrator udostępnia zebrane dane osobowe Klienta wybranemu przewoźnikowi lub pośrednikowi realizującemu przesyłki na zlecenie Administratora.",
      "   b/ W przypadku Klienta, który korzysta w Sklepie internetowym ze sposobu płatności elektronicznych lub kartą płatniczą Administrator udostępnia zebrane dane osobowe Klienta, wybranemu podmiotowi obsługującemu powyższe płatności w Sklepie internetowym.",
      "4/ Klient ma prawo dostępu do treści swoich danych oraz ich poprawiania.",
      "5/ Podanie danych osobowych jest dobrowolne, aczkolwiek niepodanie wskazanych w Regulaminie danych osobowych niezbędnych do zawarcia Umowy Sprzedaży skutkuje brakiem możliwości zawarcia tejże umowy.",
    ],
  },
  {
    title: "§ 14 Postanowienia końcowe",
    content: [
      "1/ Umowy zawierane poprzez Sklep internetowy zawierane są w języku polskim.",
      "2/ Sprzedawca zastrzega sobie prawo do dokonywania zmian Regulaminu z ważnych przyczyn to jest: zmiany przepisów prawa, zmiany sposobów płatności i dostaw – w zakresie, w jakim te zmiany wpływają na realizację postanowień niniejszego Regulaminu. O każdej zmianie Sprzedawca poinformuje Klienta z co najmniej 7 dniowym wyprzedzeniem.",
      "3/ W sprawach nieuregulowanych w niniejszym Regulaminie mają zastosowanie powszechnie obowiązujące przepisy prawa polskiego, w szczególności: Kodeksu cywilnego, ustawy prawo autorskie, ustawy o świadczeniu usług drogą elektroniczną; ustawy o prawach konsumenta, ustawy o ochronie danych osobowych.",
      "4/ Klient ma prawo skorzystać z pozasądowych sposobów rozpatrywania reklamacji i dochodzenia roszczeń. W tym celu może złożyć skargę za pośrednictwem unijnej platformy internetowej ODR dostępnej pod adresem: http://ec.europa.eu/consumers/odr/.",
    ],
  },
];
